export const REPORT_DAYS = {
  ONE_WEEK: "ONE_WEEK",
  ONE_MONTH: "ONE_MONTH",
  THREE_MONTH: "THREE_MONTH",
  SIX_MONTH: "SIX_MONTH",
  ONE_YEAR: "ONE_YEAR",
  THREE_YEAR: "THREE_YEAR",
  SEND_MAIL: "ALL",
}
