import { DJ_KEYWORD } from "constants/ActionTypes";
import {
  EQUALS,
  GREATER_THAN_OR_EQUAL,
  IN,
  LESS_THAN_OR_EQUAL,
} from "./FilterOperators";
export const KYCFilter = [
  {
    fieldSystemName: "individualRequest.gender",
    property: "gender",
    type: "SELECTED",
    label: "gender",
    dataSelect: "GENDER",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Gender",
  },
  {
    fieldSystemName: "keywords",
    property: "keywords",
    type: "SELECTED",
    label: "keywords",
    dataSelect: "KEYWORDS",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "KycIndividualMatchKeyWords",
  },
  {
    fieldSystemName: "status",
    property: "status",
    type: "SELECTED",
    label: "status",
    dataSelect: "STATUS",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "KycRequestStatus",
  },
  {
    fieldSystemName: "enableReScreening",
    property: "enableReScreening",
    type: "SELECTED",
    label: "kyc.filter.rescreening",
    dataSelect: "ACTIVE_DISABLED",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Boolean",
  },
  {
    fieldSystemName: "enableOnGoingMonitoring",
    property: "enableOnGoingMonitoring",
    type: "SELECTED",
    label: "kyc.filter.ongoingmonitoring",
    dataSelect: "ACTIVE_DISABLED",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Boolean",
  },
  {
    fieldSystemName: "individualRiskScore.riskLevel",
    property: "riskLevel",
    type: "SELECTED",
    label: "risk-level",
    dataSelect: "RISK_LEVEL",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "RiskLevel",
  },
  {
    fieldSystemName: "individualRequest.nationality",
    property: "nationality",
    type: "SELECTED",
    label: "kyc.Nationality",
    dataSelect: "NATIONALITY",
    operator: IN,
    search: true,
    selectAll: true,
    valueType: "String",
  },
  {
    fieldSystemName: "assignee",
    property: "assignee",
    type: "SELECTED",
    label: "kyc.Assignee",
    dataSelect: "USER",
    operator: IN,
    search: true,
    selectAll: true,
    valueType: "Long",
  },
  {
    fieldSystemName: "kycBlacklistMatches.kycBlacklist.categories.id",
    property: "blacklist",
    type: "SELECTED",
    label: "kyc.Blacklist",
    dataSelect: "CATEGORY",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Long",
  },
  {
    property: "riskScore",
    type: "RISK_FILTER",
    label: "kyc.filter.riskScore",
    children: [
      {
        fieldSystemName: "isSanction",
        property: "isSanction",
        operator: EQUALS,
        parent: "riskScore",
        valueType: "Boolean",
      },
      {
        fieldSystemName: "fromRisk",
        property: "fromRisk",
        operator: GREATER_THAN_OR_EQUAL,
        parent: "riskScore",
        valueType: "Float",
      },
      {
        fieldSystemName: "toRisk",
        property: "toRisk",
        operator: LESS_THAN_OR_EQUAL,
        parent: "riskScore",
        valueType: "Float",
      },
      {
        fieldSystemName: "noScore",
        property: "noScore",
        operator: EQUALS,
        parent: "riskScore",
        valueType: "Boolean",
      },
    ],
  },
];

export const DJKYCFilter = [
  {
    fieldSystemName: "individualRequest.gender",
    property: "gender",
    type: "SELECTED",
    label: "gender",
    dataSelect: "GENDER",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Gender",
  },
  {
    fieldSystemName: "keywords",
    property: "keywords",
    type: "SELECTED",
    label: "keywords",
    dataSelect: "KEYWORDS",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "String",
    list: DJ_KEYWORD,
  },
  {
    fieldSystemName: "status",
    property: "status",
    type: "SELECTED",
    label: "status",
    dataSelect: "STATUS",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "KycRequestStatus",
  },
  {
    fieldSystemName: "enableOnGoingMonitoring",
    property: "enableOnGoingMonitoring",
    type: "SELECTED",
    label: "kyc.filter.ongoingmonitoring",
    dataSelect: "ACTIVE_DISABLED",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Boolean",
    fullWidth: true,
  },
  {
    fieldSystemName: "individualRiskScore.riskLevel",
    property: "riskLevel",
    type: "SELECTED",
    label: "risk-level",
    dataSelect: "RISK_LEVEL",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "RiskLevel",
  },
  {
    fieldSystemName: "individualRequest.nationality",
    property: "nationality",
    type: "SELECTED",
    label: "kyc.Nationality",
    dataSelect: "NATIONALITY",
    operator: IN,
    search: true,
    selectAll: true,
    valueType: "String",
  },
  {
    fieldSystemName: "assignee",
    property: "assignee",
    type: "SELECTED",
    label: "kyc.Assignee",
    dataSelect: "USER",
    operator: IN,
    search: true,
    selectAll: true,
    valueType: "Long",
  },
  {
    fieldSystemName: "kycBlacklistMatches.kycBlacklist.categories.id",
    property: "blacklist",
    type: "SELECTED",
    label: "kyc.Blacklist",
    dataSelect: "CATEGORY",
    operator: IN,
    search: false,
    selectAll: false,
    valueType: "Long",
  },
  {
    property: "riskScore",
    type: "RISK_FILTER",
    label: "kyc.filter.riskScore",
    children: [
      {
        fieldSystemName: "isSanction",
        property: "isSanction",
        operator: EQUALS,
        parent: "riskScore",
        valueType: "Boolean",
      },
      {
        fieldSystemName: "fromRisk",
        property: "fromRisk",
        operator: GREATER_THAN_OR_EQUAL,
        parent: "riskScore",
        valueType: "Float",
      },
      {
        fieldSystemName: "toRisk",
        property: "toRisk",
        operator: LESS_THAN_OR_EQUAL,
        parent: "riskScore",
        valueType: "Float",
      },
      {
        fieldSystemName: "noScore",
        property: "noScore",
        operator: EQUALS,
        parent: "riskScore",
        valueType: "Boolean",
      },
    ],
  },
];
