export const KYC_STATUS = {
  PENDING: "PENDING",
  UNRESOLVED: "UNRESOLVED",
  COMPLETED: "COMPLETED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  NO_MATCH: "NO_MATCH",
  POSITIVE_MATCH: "POSITIVE_MATCH"
};
