import {
  MODE,
  RISK_ASSESSMENT,
  RISK_ASSESSMENT_KYT,
  OTHER,
} from "constants/ActionTypes";
import {
  GREATER_THAN_OR_EQUAL,
  IN,
  LESS_THAN_OR_EQUAL,
  BETWEEN,
} from "./FilterOperators";
export const KYT_REPORT = [
  {
    name: "report.table.filter.Mode",
    TableName: MODE,
    filterData: [
      {
        fieldSystemName: "assignee",
        property: "assignee",
        type: "SELECTED_ICON",
        label: "report.table.select.user",
        dataSelect: "USER",
        operator: IN,
        search: true,
        selectAll: false,
        valueType: "Long",
        labelMany: "report.users",
        labelOne: "report.user",
        maximumValues: 2,
      },
      {
        fieldSystemName: "dateOfBirth",
        property: "dateOfBirth",
        type: "DATE_TIME_FILTER",
        label: "setting.blacklist.filter.dateOfBirth",
        dataSelect: "DATE_TIME_FILTER",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "Date",
        children: [
          {
            tabName: "creation",
            tabChildren: [
              {
                fieldSystemName: "createdAt",
                property: "createdAt",
                type: "SELECTED",
                label: "report.selectDate",
                dataSelect: "DATE_TIME_FILTER",
                operator: BETWEEN,
                search: true,
                selectAll: false,
                valueType: "Date",
                name: "report.table.DateCreated",
                labelMany: "report.table.DateCreated",
                labelOne: "report.table.DateCreated",
                maximumMonths: 6,
              },

              {
                fieldSystemName: "createdBy",
                property: "createdBy",
                type: "SELECTED",
                label: "report.table.select.user",
                dataSelect: "USER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Long",
                name: "report.table.CreatedBy",
                labelMany: "report.users",
                labelOne: "report.user",
                maximumValues: 2,
              },
            ],
          },
          {
            tabName: "modification",
            tabChildren: [
              {
                fieldSystemName: "updatedAt",
                property: "updatedAt",
                type: "SELECTED",
                label: "report.selectDate",
                dataSelect: "DATE_TIME_FILTER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Date",
                name: "report.LastModifiedOn",
                labelMany: "report.table.DateCreated",
                labelOne: "report.table.DateCreated",
                maximumMonths: 6,
              },
              {
                fieldSystemName: "lastModifiedBy",
                property: "lastModifiedBy",
                type: "SELECTED",
                label: "report.table.select.user",
                dataSelect: "USER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Long",
                name: "last-modified-by",
                labelMany: "report.users",
                labelOne: "report.user",
                maximumValues: 2,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "report.table.filter.RiskAssessment",
    TableName: RISK_ASSESSMENT,
    filterData: [
      {
        fieldSystemName: "addressDetails.risk.riskLevel",
        property: "riskLevel",
        type: "SELECTED",
        label: "report.table.select.level",
        dataSelect: "RISK_LEVEL",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "RiskLevel",
        name: "report.table.RiskLevel",
        labelMany: "report.levels",
        labelOne: "report.level",
      },
      {
        fieldSystemName: "addressDetails.risk.risk",
        property: "riskScore",
        type: "SELECTED",
        label: "report.riskScore",
        dataSelect: "RISK_SCORE",
        operator: IN,
        search: false,
        selectAll: false,
        name: "kyc.filter.riskScore",
        labelMany: "report.levels",
        labelOne: "report.level",
        padding: true,
        valueType: "Float",
      },
    ],
  },

  {
    name: "report.table.filter.Others",
    TableName: OTHER,
    filterData: [
      {
        fieldSystemName: "asset",
        property: "asset",
        type: "SELECTED",
        label: "report.selectAssetType",
        dataSelect: "ASSET",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "Asset",
        name: "kyt.filter.asset",
        labelMany: "report.types",
        labelOne: "report.type",
        maximumValues: 2,
      },
      {
        fieldSystemName: "addressDetails.wallet.country",
        property: "country",
        type: "SELECTED_ICON",
        label: "report.table.select.country",
        dataSelect: "COUNTRY",
        operator: IN,
        search: true,
        selectAll: false,
        valueType: "String",
        name: "report.table.country",
        padding: true,
        labelMany: "report.countries",
        labelOne: "report.country",
        maximumValues: 4,
      },
      {
        fieldSystemName: "groupList",
        property: "groupList",
        type: "SELECTED",
        label: "report.table.select.group",
        dataSelect: "GROUP_LIST_KYT",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "Long",
        name: "report.table.GroupList",
        labelMany: "report.GroupLists",
        labelOne: "report.GroupList",
        padding: true,
        maximumValues: 2,
      },
    ],
  },
];
