import { DJ_KEYWORD } from "constants/ActionTypes";
import {
  MODE,
  RISK_ASSESSMENT,
  GROUP_LIST,
  OTHER,
} from "constants/ActionTypes";
import {
  EQUALS,
  GREATER_THAN_OR_EQUAL,
  IN,
  LESS_THAN_OR_EQUAL,
  BETWEEN,
} from "./FilterOperators";
export const KYC_REPORT_DJ = [
  {
    name: "report.table.filter.Mode",
    TableName: MODE,
    filterData: [
      {
        fieldSystemName: "assignee",
        property: "assignee",
        type: "SELECTED_ICON",
        label: "report.table.select.user",
        dataSelect: "USER",
        operator: IN,
        search: true,
        selectAll: false,
        valueType: "Long",
        labelMany: "report.users",
        labelOne: "report.user",
        maximumValues: 2,
      },
      {
        fieldSystemName: "dateOfBirth",
        property: "dateOfBirth",
        type: "DATE_TIME_FILTER",
        label: "setting.blacklist.filter.dateOfBirth",
        dataSelect: "DATE_TIME_FILTER",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "Date",
        children: [
          {
            tabName: "creation",
            tabChildren: [
              {
                fieldSystemName: "createdAt",
                property: "createdAt",
                type: "SELECTED",
                label: "report.selectDate",
                dataSelect: "DATE_TIME_FILTER",
                operator: BETWEEN,
                search: true,
                selectAll: false,
                valueType: "Date",
                name: "report.table.DateCreated",
                labelMany: "report.table.DateCreated",
                labelOne: "report.table.DateCreated",
                maximumMonths: 6,
              },

              {
                fieldSystemName: "createdBy",
                property: "createdBy",
                type: "SELECTED",
                label: "report.table.select.user",
                dataSelect: "USER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Long",
                name: "report.table.CreatedBy",
                labelMany: "report.users",
                labelOne: "report.user",
                maximumValues: 2,
              },
            ],
          },
          {
            tabName: "modification",
            tabChildren: [
              {
                fieldSystemName: "updatedAt",
                property: "updatedAt",
                type: "SELECTED",
                label: "report.selectDate",
                dataSelect: "DATE_TIME_FILTER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Date",
                name: "report.LastModifiedOn",
                labelMany: "report.table.DateCreated",
                labelOne: "report.table.DateCreated",
                maximumMonths: 6,
              },
              {
                fieldSystemName: "lastModifiedBy",
                property: "lastModifiedBy",
                type: "SELECTED",
                label: "report.selectDate",
                dataSelect: "USER",
                operator: IN,
                search: true,
                selectAll: false,
                valueType: "Long",
                name: "last-modified-by",
                labelMany: "report.users",
                labelOne: "report.user",
                maximumValues: 2,
              },
            ],
          },
        ],
      },
    ],
  },
  {
    name: "report.table.filter.RiskAssessment",
    TableName: RISK_ASSESSMENT,
    filterData: [
      {
        fieldSystemName: "individualRiskScore.riskLevel",
        property: "riskLevel",
        type: "SELECTED",
        label: "report.table.select.level",
        dataSelect: "RISK_LEVEL",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "RiskLevel",
        name: "report.table.RiskLevel",
        labelMany: "report.levels",
        labelOne: "report.level",
      },
      {
        name: "report.table.RiskScore",
        property: "riskScore",
        type: "RISK_FILTER",
        label: "kyc.filter.riskScore",
        children: [
          {
            fieldSystemName: "isSanction",
            property: "isSanction",
            operator: EQUALS,
            parent: "riskScore",
            valueType: "Boolean",
          },
          {
            fieldSystemName: "fromRisk",
            property: "fromRisk",
            operator: GREATER_THAN_OR_EQUAL,
            parent: "riskScore",
            valueType: "Float",
          },
          {
            fieldSystemName: "toRisk",
            property: "toRisk",
            operator: LESS_THAN_OR_EQUAL,
            parent: "riskScore",
            valueType: "Float",
          },
          {
            fieldSystemName: "noScore",
            property: "noScore",
            operator: EQUALS,
            parent: "riskScore",
            valueType: "Boolean",
          },
        ],
        padding: true,
      },
    ],
  },
  {
    name: "report.table.filter.GroupList",
    TableName: GROUP_LIST,
    filterData: [
      {
        fieldSystemName: "groupList",
        property: "groupList",
        type: "SELECTED",
        label: "report.table.select.group",
        dataSelect: "GROUP_LIST_DJ_KYC",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "Long",
        name: "report.table.GroupList",
        labelMany: "report.GroupLists",
        labelOne: "report.GroupList",
        maximumValues: 2,
      },
      {
        fieldSystemName: "status",
        property: "status",
        type: "SELECTED",
        label: "report.table.select.status",
        labelMany: "report.status",
        labelOne: "report.status",
        dataSelect: "STATUS",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "KycRequestStatus",
        name: "report.table.Status",
        padding: true,
      },
    ],
  },
  {
    name: "report.table.filter.Others",
    TableName: OTHER,
    filterData: [
      {
        fieldSystemName: "individualRequest.nationality",
        property: "nationality",
        type: "SELECTED_ICON",
        label: "report.table.select.nationality",
        dataSelect: "NATIONALITY_DJ",
        operator: IN,
        search: true,
        selectAll: false,
        valueType: "String",
        name: "report.table.Nationality",
        labelMany: "report.nationalities",
        labelOne: "report.nationality",
        maximumValues: 4,
      },
      {
        fieldSystemName: "keywords",
        property: "keywords",
        type: "SELECTED",
        label: "report.table.select.keyword",
        dataSelect: "KEYWORDS",
        operator: IN,
        search: false,
        selectAll: false,
        valueType: "String",
        name: "report.table.Keyword",
        padding: true,
        labelMany: "report.keywords",
        labelOne: "report.keyword",
        maximumValues: 2,
        list: DJ_KEYWORD,
      },
    ],
  },
];
