export const templateExampleForImportKytCsv = {
  headers: [
    {
      label: "case.detail.table.kyt.header.walletAddress",
      key: "wallet_address",
    },
    { label: "case.detail.table.kyt.header.assetType", key: "asset_type" },
    { label: "case.detail.individualRequest.referenceId", key: "reference_id" },
    { label: "kyt.enableOngoingMonitoring", key: "enable_ongoing_monitoring" },
    { label: "kyt.assignee", key: "assignee" },
  ],
  data: [
    {
      wallet_address: "0x8d12a197cb00d4747a1fe03395095ce2a...",
      asset_type: "ETH",
      reference_id: "Reference (Internal)",
      enable_ongoing_monitoring: "FALSE",
      assignee: "assignee@email.com",
    },
  ],
};

export const templateExampleForImportKycCsv = {
  headers: [
    { label: "form.firstName", key: "first_name" },
    { label: "form.middleName", key: "middle_name" },
    { label: "form.lastName", key: "last_name" },
    { label: "gender", key: "gender" },
    { label: "appModule.requestForm.email", key: "email" },
    { label: "appModule.phone", key: "phone" },
    { label: "address-line-1", key: "address_1" },
    { label: "address-line-2", key: "address_2" },
    { label: "kyc.DateOfBirth", key: "date_of_birth" },
    { label: "screening.result.Yob", key: "year_of_birth" },
    { label: "screening.result.Pob", key: "place_of_birth" },
    { label: "kyc.Nationality", key: "nationality" },
    { label: "kyc.countryOfResidence", key: "country_of_residence" },
    {
      label: "case.detail.individualRequest.governmentId",
      key: "government_id_number",
    },
    { label: "kyc.idIssuingCountry", key: "id_issuing_country" },
    { label: "kyc.referenceId", key: "reference" },
    { label: "kyc.enableReScreening", key: "enable_re_screening" },
    { label: "kyc.enableOngoingMonitoring", key: "enable_ongoing_monitoring" },
    { label: "kyc.Assignee", key: "assignee" },
  ],
};
export const templateExampleForImportDjKycCsv = {
  headers: [
    { label: "form.fullName", key: "full_name" },
    { label: "form.firstName", key: "first_name" },
    { label: "form.middleName", key: "middle_name" },
    { label: "form.lastName", key: "last_name" },
    { label: "form.profileNotes", key: "profile_notes" },
    { label: "form.occupationTitles", key: "occupation_titles" },
    { label: "gender", key: "gender" },
    { label: "appModule.requestForm.email", key: "email" },
    { label: "appModule.phone", key: "phone" },
    { label: "address-line-1", key: "address_1" },
    { label: "address-line-2", key: "address_2" },
    { label: "kyc.DateOfBirth", key: "date_of_birth" },
    { label: "form.strictDateMatch", key: "strict_date_match" },
    { label: "screening.result.Yob", key: "year_of_birth" },
    { label: "screening.result.Pob", key: "place_of_birth" },
    { label: "kyc.Nationality", key: "nationality" },
    { label: "kyc.countryOfResidence", key: "country_of_residence" },
    {
      label: "case.detail.individualRequest.governmentId",
      key: "government_id_number",
    },
    { label: "kyc.idIssuingCountry", key: "id_issuing_country" },
    { label: "kyc.referenceId", key: "reference" },
    { label: "kyc.enableReScreening", key: "enable_re_screening" },
    { label: "kyc.enableOngoingMonitoring", key: "enable_ongoing_monitoring" },
    { label: "kyc.Assignee", key: "assignee" },
  ],
};
export const templateExampleForImportKybCsv = {
  headers: [
    { label: "kyb.businessName", key: "business_name" },
    { label: "form.businessIDNumber", key: "business_id_number" },
    { label: "address-line-1", key: "address_1" },
    { label: "address-line-2", key: "address_2" },
    { label: "kyb.sizeOfCompany", key: "size_of_company" },
    { label: "email-address", key: "email_address" },
    { label: "kyb.Website", key: "website" },
    { label: "kyc.referenceId", key: "reference" },
    { label: "kyb.NatureOfBusiness", key: "nature_of_business" },
    { label: "kyb.companyType", key: "company_type" },
    { label: "form.countryOfIncorporation", key: "country_of_incorporation" },
    { label: "kyb.CountryOfHeadquarter", key: "country_of_headquarter" },
    { label: "kyb.DateOfIncorporation", key: "date_of_incorporation" },
    { label: "kyb.phoneNumber", key: "phone_number" },
    { label: "kyb.Relationship", key: "relationship" },
    { label: "kyb.enableReScreening", key: "enable_re_screening" },
    { label: "kyb.enableOngoingMonitoring", key: "enable_ongoing_monitoring" },
    { label: "kyb.Assignee", key: "assignee" },
  ],
};
export const templateExampleForImportKycBlacklistCsv = {
  headers: [
    { label: "form.firstName", key: "first_name" },
    { label: "form.middleName", key: "middle_name" },
    { label: "form.lastName", key: "last_name" },
    { label: "gender", key: "gender" },
    { label: "email-address", key: "email" },
    { label: "setting.blacklist.dialog.phone", key: "phone" },
    { label: "setting.blacklist.dialog.address", key: "address" },
    { label: "setting.blacklist.table.dateOfBirth", key: "dateOfBirth" },
    { label: "setting.blacklist.dialog.place.birth", key: "placeOfBirth" },
    { label: "setting.blacklist.table.nationality", key: "nationality" },
    { label: "setting.blacklist.table.country", key: "countryOfResidence" },
    { label: "setting.blacklist.table.category", key: "category" },
    { label: "setting.blacklist.dialog.id.country", key: "idIssuingCountry" },
    { label: "setting.blacklist.dialog.further", key: "furtherInformation" },
  ],
};
