const ACL = {
  CASE_MODULE_VIEW: "CASE_MODULE.VIEW",
  //KYC
  KYC_APPROVE_REJECT: "KYC_APPROVE_REJECT.EDIT",
  KYC_MODULE_VIEW: "KYC_MODULE.VIEW",
  MY_KYC_VIEW: "MY_KYC.VIEW",
  MY_KYC_EDIT: "MY_KYC.EDIT",
  KYC_MODULE_CREATE: "KYC_MODULE.CREATE",
  KYC_STATUS_RESOLUTION: "KYC_STATUS_RESOLUTION.EDIT",
  //DowJone
  DJ_KYC_APPROVE_REJECT: "DJ_KYC_APPROVE_REJECT.EDIT",
  DJ_KYC_MODULE_VIEW: "DJ_KYC_MODULE.VIEW",
  DJ_MY_KYC_VIEW: "DJ_MY_KYC.VIEW",
  DJ_MY_KYC_EDIT: "DJ_MY_KYC.EDIT",
  DJ_KYC_MODULE_CREATE: "DJ_KYC_MODULE.CREATE",
  DJ_KYC_STATUS_RESOLUTION: "DJ_KYC_STATUS_RESOLUTION.EDIT",
  //KYB
  KYB_MODULE_VIEW: "KYB_MODULE.VIEW",
  KYB_MODULE_CREATE: "KYB_MODULE.CREATE",
  MY_KYB_VIEW: "MY_KYB.VIEW",
  MY_KYB_EDIT: "MY_KYB.EDIT",
  KYB_STATUS_RESOLUTION: "KYB_STATUS_RESOLUTION.EDIT",
  KYB_APPROVE_REJECT: "KYB_APPROVE_REJECT.EDIT",
  //KYT
  KYT_MODULE_VIEW: "KYT_MODULE.VIEW",
  KYT_MODULE_CREATE: "KYT_MODULE.CREATE",
  MY_KYT_VIEW: "MY_KYT.VIEW",
  MY_KYT_EDIT: "MY_KYT.EDIT",
  KYT_APPROVE_REJECT: "KYT_APPROVE_REJECT.EDIT",
  //AUDIT
  AUDIT_MODULE_VIEW: "AUDIT_MODULE.VIEW",
  //STAFF
  STAFF_MODULE_VIEW: "STAFF_MODULE.VIEW",
  STAFF_MODULE_CREATE: "STAFF_MODULE.CREATE",
  STAFF_MODULE_EDIT: "STAFF_MODULE.EDIT",
  STAFF_MODULE_DELETE: "STAFF_MODULE.DELETE",
  //SETTING
  SETTING_MODULE_VIEW: "SETTING_MODULE.VIEW",
  SETTING_KYC_VIEW: "SETTING_KYC.VIEW",
  SETTING_KYC_EDIT: "SETTING_KYC.EDIT",
  SETTING_KYB_VIEW: "SETTING_KYB.VIEW",
  SETTING_KYB_EDIT: "SETTING_KYB.EDIT",
  SETTING_KYT_VIEW: "SETTING_KYT.VIEW",
  SETTING_KYT_EDIT: "SETTING_KYT.EDIT",
  SETTING_SECURITY_VIEW: "SECURITY.VIEW",
  SETTING_SECURITY_EDIT: "SECURITY.EDIT",
  SETTING_BLACKLIST_VIEW: "BLACKLIST.VIEW",
  SETTING_BLACKLIST_CREATE: "BLACKLIST.CREATE",
  SETTING_BLACKLIST_EDIT: "BLACKLIST.EDIT",
  SETTING_BLACKLIST_DELETE: "BLACKLIST.DELETE",
  //Package Information
  PACKAGE_INFORMATION_VIEW: "PACKAGE_INFORMATION.VIEW",
  //locked function
  LOCKED_FUNCTION_EDIT: "LOCKED_FUNCTION.EDIT",
  //Department
  DEPARTMENT_MODULE_VIEW: "DEPARTMENT_MODULE.VIEW",
  DEPARTMENT_MODULE_CREATE: "DEPARTMENT_MODULE.CREATE",
  DEPARTMENT_MODULE_EDIT: "DEPARTMENT_MODULE.EDIT",
  DEPARTMENT_MODULE_DELETE: "DEPARTMENT_MODULE.DELETE",
};

export default ACL;
